name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v1

      - name: Build Images
        run: make build

      - name: Publish Images
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo $PASSWORD | docker login -u $USERNAME --password-stdin
          make push
